name: RTM-REM
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _py-xgboost-mutex=2.0
  - _tflow_select=2.3.0
  - absl-py=1.4.0
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - alsa-lib=1.2.8
  - anyio=4.0.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=0.17.0
  - astor=0.8.1
  - asttokens=2.4.0
  - astunparse=1.6.3
  - async-lru=2.0.4
  - async-timeout=4.0.3
  - attr=2.5.1
  - attrs=23.1.0
  - babel=2.12.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - beautifulsoup4=4.12.2
  - bleach=6.0.0
  - blinker=1.6.2
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.3.1
  - cairo=1.16.0
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - comm=0.1.4
  - cryptography=41.0.3
  - cycler=0.11.0
  - cytoolz=0.12.2
  - dask-core=2022.12.1
  - dbus=1.13.6
  - debugpy=1.7.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - enum34=1.1.10
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fqdn=1.5.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - fsspec=2023.10.0
  - gast=0.3.3
  - gettext=0.21.1
  - glib=2.76.4
  - glib-tools=2.76.4
  - gmp=6.2.1
  - google-auth=2.22.0
  - google-auth-oauthlib=1.0.0
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.57.0
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - h5py=2.10.0
  - harfbuzz=7.3.0
  - hdf5=1.10.5
  - icu=72.1
  - idna=3.4
  - imagecodecs-lite=2019.12.3
  - imageio=2.31.5
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - ipykernel=6.25.2
  - ipython=8.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.0
  - isoduration=20.11.0
  - jedi=0.19.0
  - jellyfish=1.0.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - json5=0.9.14
  - jsonpointer=2.0
  - jsonschema=4.19.0
  - jsonschema-specifications=2023.7.1
  - jsonschema-with-format-nongpl=4.19.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.3.1
  - jupyter_console=6.6.3
  - jupyter_core=4.12.0
  - jupyter_events=0.7.0
  - jupyter_server=2.7.3
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.0.5
  - jupyterlab_pygments=0.2.2
  - jupyterlab_server=2.24.0
  - jupyterlab_widgets=3.0.8
  - keras=2.4.3
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.3
  - libblas=3.9.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=16.0.6
  - libclang13=16.0.6
  - libcups=2.3.3
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc-ng=13.1.0
  - libgcrypt=1.10.1
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - libglib=2.76.4
  - libgomp=13.1.0
  - libgpg-error=1.47
  - libgrpc=1.57.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.23
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=4.23.3
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libstdcxx-ng=13.1.0
  - libsystemd0=254
  - libtiff=4.5.1
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.1
  - libxcb=1.15
  - libxgboost=1.7.6
  - libxkbcommon=1.5.0
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lime=0.2.0.1
  - locket=1.0.0
  - lz4-c=1.9.4
  - markdown=3.4.4
  - markupsafe=2.1.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - matplotlib-inline=0.1.6
  - mistune=3.0.1
  - mpg123=1.31.3
  - multidict=6.0.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.8.0
  - nbconvert=7.8.0
  - nbconvert-core=7.8.0
  - nbconvert-pandoc=7.8.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - nltk=3.8.1
  - notebook=7.0.3
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.92
  - numpy=1.19.5
  - oauthlib=3.2.2
  - openjpeg=2.5.0
  - openssl=3.1.4
  - opt_einsum=3.3.0
  - overrides=7.4.0
  - packaging=23.1
  - pandas=1.4.4
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - partd=1.4.1
  - pathlib=1.0.1
  - patsy=0.5.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.0
  - pip=23.2.1
  - pixman=0.40.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - prometheus_client=0.17.1
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - protobuf=4.23.3
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - py-xgboost=1.7.6
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.16.1
  - pyjwt=2.8.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.8.17
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.18.0
  - python-json-logger=2.0.7
  - python_abi=3.8
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pywavelets=1.4.1
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - qt-main=5.15.8
  - qtconsole=5.4.4
  - qtconsole-base=5.4.4
  - qtpy=2.4.0
  - re2=2023.03.02
  - readline=8.2
  - referencing=0.30.2
  - regex=2023.8.8
  - requests=2.31.0
  - requests-oauthlib=1.3.1
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.10.2
  - rsa=4.9
  - scikit-image=0.19.3
  - scikit-learn=0.23.2
  - scipy=1.8.1
  - seaborn=0.12.2
  - seaborn-base=0.12.2
  - send2trash=1.8.2
  - setuptools=68.1.2
  - sip=6.7.11
  - six=1.16.0
  - sniffio=1.3.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.13.5
  - tensorboard=2.14.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.6.0
  - termcolor=2.3.0
  - terminado=0.17.1
  - threadpoolctl=3.2.0
  - tifffile=2019.7.26.2
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.9.0
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - typing_utils=0.1.0
  - uri-template=1.3.0
  - urllib3=1.26.15
  - wcwidth=0.2.6
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.6.2
  - werkzeug=2.3.7
  - wheel=0.41.2
  - widgetsnbextension=4.0.8
  - wrapt=1.15.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xgboost=1.7.6
  - xkeyboard-config=2.39
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.6
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.4
  - zipp=3.16.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - cvxopt==1.3.2
      - deprecation==2.1.0
      - intervaltree==3.1.0
      - lxml==4.9.3
      - pm4py==2.7.8.4
      - pydotplus==2.0.2
      - python-graphviz==0.20.1
      - sortedcontainers==2.4.0
      - stringdist==1.0.9
